export const DO_LOGIN_REQUEST_INIT = 'DO_LOGIN_REQUEST_INIT';
export const DO_LOGIN_REQUEST_SUCCESS = 'DO_LOGIN_REQUEST_SUCCESS';
export const DO_LOGIN_REQUEST_ERROR = 'DO_LOGIN_REQUEST_ERROR';

export const DO_LOGOUT_REQUEST_SUCCESS = 'DO_LOGOUT_REQUEST_SUCCESS';
export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR';

export const REGISTER_REQUEST_INIT = 'REGISTER_REQUEST_INIT';
export const REGISTER_REQUEST_SUCCESS = 'REGISTER_REQUEST_SUCCESS';
export const REGISTER_REQUEST_ERROR = 'REGISTER_REQUEST_ERROR';

export const TOGGLE_LOADER = 'TOGGLE_LOADER';

export const GET_PRODUCTS_REQUEST_INIT = 'GET_PRODUCTS_REQUEST_INIT';
export const GET_PRODUCTS_REQUEST_SUCCESS = 'GET_PRODUCTS_REQUEST_SUCCESS';
export const GET_PRODUCTS_REQUEST_ERROR = 'GET_PRODUCTS_REQUEST_ERROR';

export const SAVE_PRODUCT_REQUEST_INIT = 'SAVE_PRODUCT_REQUEST_INIT';
export const SAVE_PRODUCT_REQUEST_SUCCESS = 'SAVE_PRODUCT_REQUEST_SUCCESS';
export const SAVE_PRODUCT_REQUEST_ERROR = 'SAVE_PRODUCT_REQUEST_ERROR';
export const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS';

export const ADD_PRODUCT_TO_BAG_INIT = 'ADD_PRODUCT_TO_BAG_INIT';
export const ADD_PRODUCT_TO_BAG_SUCCESS = 'ADD_PRODUCT_TO_BAG_SUCCESS';
export const ADD_PRODUCT_TO_BAG_ERROR = 'ADD_PRODUCT_TO_BAG_ERROR';

export const GET_BAG_INIT = 'GET_BAG_INIT';
export const GET_BAG_SUCCESS = 'GET_BAG_SUCCESS';
export const GET_BAG_ERROR = 'GET_BAG_ERROR';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const SHOW_BAG_MODAL = 'SHOW_BAG_MODAL';
export const HIDE_BAG_MODAL = 'HIDE_BAG_MODAL';